// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE',
    appId: '1:162993444111:android:0cf43b8bcf94ecb3c1da7a',
    messagingSenderId: '162993444111',
    projectId: 'bookswap-app-e29b4',
    storageBucket: 'bookswap-app-e29b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE',
    appId: '1:162993444111:ios:8e3542085b5745bfc1da7a',
    messagingSenderId: '162993444111',
    projectId: 'bookswap-app-e29b4',
    storageBucket: 'bookswap-app-e29b4.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE',
    appId: '1:162993444111:web:0e09933150ad80bec1da7a',
    messagingSenderId: '162993444111',
    projectId: 'bookswap-app-e29b4',
    authDomain: 'bookswap-app-e29b4.firebaseapp.com',
    storageBucket: 'bookswap-app-e29b4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: '1:162993444111:ios:8e3542085b5745bfc1da7a',
    messagingSenderId: '162993444111',
    projectId: 'bookswap-app-e29b4',
    storageBucket: 'bookswap-app-e29b4.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY_HERE',
    appId: '1:162993444111:web:2db668bf2d00aac0c1da7a',
    messagingSenderId: '162993444111',
    projectId: 'bookswap-app-e29b4',
    authDomain: 'bookswap-app-e29b4.firebaseapp.com',
    storageBucket: 'bookswap-app-e29b4.firebasestorage.app',
  );

}